### ISSUE TITLE
Contents of SourceCode/utils/vgui/lib/win32_vc6 are missing

### ISSUE THREAD

**Issue by SamVanheer** [malortie/uncompleted-compilable-hl-opfor#1]
This directory contains the import library to link with VGUI1. By default import libraries are ignored when adding files to git so you'll need to use `git add -f vgui.lib` to force add it.

**Comment by malortie** [comment]
@SamVanheer 

Thank you!

I also spotted other missing files. In fact, every .lib file was missing.

I uploaded the missing files. Please see this commit:

https://github.com/malortie/uncompleted-compilable-hl-opfor/commit/8aa4bdcb3a4e8d1599ad206951383529be6da932

**Comment by SamVanheer** [comment]
The libraries in `SourceCode/lib` should be in `SourceCode/lib/public` since that's where the client dll project is referencing them from.

**Comment by malortie** [comment]
The libraries have been moved to the correct folder.

Please see this commit:
https://github.com/malortie/uncompleted-compilable-hl-opfor/commit/7ff1b175af884aea3ce26cea0dbb461b7cea6120
