### ISSUE TITLE
Projects target a specific WindowsTargetPlatformVersion

### ISSUE THREAD

**Issue by SamVanheer** [malortie/uncompleted-compilable-hl-opfor#3]
Both the client and server target a specific WindowsTargetPlatformVersion, which requires the corresponding SDK to be installed. It isn't really necessary to specify a particular version. I removed it and it defaulted to 8.1 for me (i'm using Windows 8.1).

**Comment by malortie** [comment]
The target platform version node has been removed from both projects.

Please see this commit:
https://github.com/malortie/uncompleted-compilable-hl-opfor/commit/a3d37d1fa0e752cf6dd695347753a6fcb5e34f58

Thank you.
