### ISSUE TITLE
can you create some dlls for a hl1 mod 

### ISSUE THREAD

**Issue by sixcentgeorge** [malortie/uncompleted-compilable-hl-opfor#4]
hello my canadian friend.. i hope you speak french and english ;'] my name is jean-christophe
i saw you are very active .. [ i am either ] i search somebody like you that knows well how to release the dlls for a hl or hl2 mods..
i already made two : opposing life2life [sp] ; assault strike [mp coop] that use gearbox and sc4.7 dlls..
these last weeks i worked and finally made a new "gigantic mod" that i named Hell-Life .
it has nearly 200 maps.. coming from mods from gearbox  [ op4 + blue shift + decay ], or half-life italia+spain websites [ azure sheep & pov ] and sweet half-life . i rework the map at the inside : the ent file .
i need new dlls because i want to use the monsters and robots coming mods that are not in gearbox dlls plus like with decay : let the player be an alien or two.. .
my goal is to have a map at end [ one of sweet half life just before ending ] where tor [from svencoop] fights the king pin in a "duel" online .. may be like the "russian bullet mobile dating" at end of fight : looser play again with a new online player or looser . winner play and other winner..
i hope to reuse what is inside my two previous mods in this new.. and later port all maps and engine to "hls-source2" or unreal [ there are a lot of good maps made at the time of sc 3 that i hope to port ] i hope to make a power of two multiplayers , multi-teams mods : here in 4x2 :  gina +colette ; gordon + gman or alyx ; kinpin + tor ; adrian + barney  or 2x4 or 8x1 .. to match consoles gaming style
here are the links to get my previous releases 
for single player mod  files are here :
https://tinyurl.com/usu82mu

for coop mod assault strike :
win files
https://tinyurl.com/rjz4vns
linux :
https://tinyurl.com/yx3cdgva

later i saw when using my maps , that a listen server is very crashy.. so i uploaded a iso that is an old linux live server that works as a live linux distro.. [ i prefer to use a server so i have different folders with files and configs.. ]
https://tinyurl.com/ufpz66z

here is copy of my post talking about the mod at steampowered forum..

https://tinyurl.com/wsrd6vd
it helps as a manual .. for the mod and iso .. do not use the memory from the vga card ; that should be the reason valve advice not to use my file... you get commands by using the arrow keys when iso is loaded.. remove parameter toram if you have less than 4 Go of ram at linux live prompt but you should be easy with linux..
if you are not easy with linux , use the command that has hlds_run .. but remove the screen at the beginning.. this tools is handling the windows of servers 
thank you in advance marc..

**Comment by malortie** [comment]
@sixcentgeorge  

À cet instant, je n'ai pas la motivation de travailler sur des projets en lien avec les mods d'HL. Je travailles présentement sur d'autres projets et je préfères ne pas m'embarquer sur un projet de cette ampleur.

Malheureusement, ma réponse est non.

Pour ce qui est de votre demande au sujet du DLL, j'ignore si créer un nouveau DLL serait vraiment nécéssaire - Il semble que Sven Coop incorpore un langage script "Angel Script" avec lequel il serait possible de créer de nouveaux monstres.

[Voici une vidéo](https://www.youtube.com/watch?v=n3lfxIPn-JU) que j'ai trouvé avec un monstre (Pitdrone d'Opposing Force) dans Sven Coop. Dans la description, il est écrit que ce monstre a été programmé à l'aide d'AngelScript.

[Voici un lien](https://github.com/baso88/SC_AngelScript/blob/SC_AngelScript/samples/scripts/maps/monster_barney_custom/monster_barney_custom.as) vers un exemple qui semble illustrer cette possibilité: 

La vidéo date d'environ 4 ans, mais si le langage script AngelScript est toujours dans SvenCoop, vous n'auriez qu'à implémenter les monstres que vous voulez.

**Comment by sixcentgeorge** [comment]
merci de ta reponse rapide et tres courtoise..je suis un ancien de chez svencoop : ou j ai ete membre du beta-test pendant quelque jours , semaines.. j ai recement rejouer et trouver tout plein de bug..mes messages ont ete efface du site de moddb .. mais il y a une copie a unreal.. : https://forums.unrealengine.com/community/general-discussion/1689415-the-steam-hungry-gab-gap  ou on voie qu un joueur avec un lag d une demi seconde : ne peut jamais jouer ou presque.. et si il entre .. il peut rester "observateur" pendant un tres long moment..   bien sur comme beaucoup d autres nullards en recherche d etre "des stars" on efface les mauvais comments et on ban les emmerdeurs de trouveurs de bugs..
en plus je prefere le mode single player car il permet d entrer et sortir plusieurs fois sur une carte sans probleme de spawn..  un autre "truc" sympa que j ai trouve dans la derniere version de xahs3d .. et qui semble etre issus d une idee que j avais ecrite en 2012 dans leur forum..
https://hlfx.ru/forum/showthread.php?s=&postid=189875#post189875
https://hlfx.ru/forum/showthread.php?threadid=3584&perpage=15&pagenumber=10#
https://github.com/FWGS/xash3d-fwgs/issues/115#issuecomment-582786810

c est le secure spawn point.. et comme le montre "la fermeture de topic "administrative" et digne de la "police du peuple de la grande urss et amerique reunies" ... y a pas un mot de credit pour moi.. meme pas merci ni merde..  

ce angel script est trop lourd et le code de svencoop fait par le fameux sniper est trop pourrie depuis toujours..comme d autres il programme , il programme mais ne verifie pas au niveau du cpu , si cela passe..
j ai mis des critiques au sujets de son model viewer de hl models qui comme le programme dont il utilise les sources : met a full load un cpu des l ouverture de la fenetre.. https://github.com/Solokiller/HL_Tools/issues  ce qui fait que le rendu video est pas parfait quand on change d animation ou sequence..
il existe amxmodx mais a svencoop ils reinventent  toujours mieux.. comme modbb qui me traite de voleurs en fermant pas page.. alors que j utilise que des mods qui sont libre de droit et surtout qui ont utiliser des parties des mods de gearbox .. voir tout le mod comme avec decay..  ou svencoop avec tout les monstres et models de op4..
je parle d un mod qui fait le double de hl.. un peu le double ruban d adn avec une ligne hl et l autre avec des mods... en un melange subtil et leger digne des la gastronomie francaise ... [LOL ]
DONC REFLECHIE ENCORE..y a pas grand chose a faire a part ajouter des armes et quelques monstres plus des entites pour que les cartes passent tres bien...  bien sur au prix d enlever des armes et des monstres inutilises.. mais je saurais etre precis..de plus je lirais le code et essayerais de trouver des erreurs.. code qui peut etre publie ici..  on fait ce premier mod  que l on vendra sur steam au prix de quelques dollars.. et apres on le porte en hl2..  [ si ceux qui ont fait des cartes ou des models viennent se plaindre et si ils ont des preuves comme des fichiers sources.. on les payera un peu selon les gains du mod..] le plus difficile dans ces histoires de sdk c est que le code corresponds a un logiciel windows qui s integre dans un windows.. windows et son patron M$ qui ces jours derniers a enterres tout support pour win7.. half life c est plutot win98 ? son sdk ..ou au plus tard windows xp..
donc tu as une mine d or de reussir a le compiler . fait le.. je suis pret a te donner une prime pour ce travail ou service rendu .. qui fera de moi et ceux de la team .. des stars de hl aux conventions..genre luke skywalker.. l avenir c est pas encore la VR avec des jeux comme alyx.. qui pour etre jouables ont besoins de pc de fils de millionnaires.. je pense plus que gmod est le digne heritier de ce que fut svencoop forum avant hl2...  gmode qui a bien reussi le passage au 64 bit .. alors que meme valve l a dropped pour hl2.. [ le 64 bit ]
allez mon pote cherche la force et pense a des big fiestas a las vegas ou hollywood ou en europe du sud entre espagne france et italie ou grece.. que je connais comme ma poche,, ou bien des sortie en heros en coree du sud et japon.. avec des nenetttes plein les bras comme des rock stars ..

**Comment by malortie** [comment]
@sixcentgeorge 

J'ai lu votre message, et je comprends votre enthousiasme dans la réalisation de ce mod, mais c'est non. Je ne veux pas travailler sur ce mod.

Si vous souhaitez incorporer de nouvelles entités via un DLL, vous devrez apprendre à programmer en C++. Voici une liste de ressources qui vous permettront d'apprendre le langage C++.

* https://www.youtube.com/watch?v=tvC1WCdV1XU&list=PL784B80DF505577CF
* https://www.learncpp.com/
* http://www.cplusplus.com/doc/tutorial/
* https://en.cppreference.com/w/cpp

Voici une page qui contient un ensemble de tutoriaux de programmation pour HL (GoldSrc).

https://twhl.info/wiki/page/category%3AGoldsource_Tutorials

Voici un tutoriel qui montre comment compiler et lancer HL à partir de Visual Studio. Je n'ai malheureusement pas trouvé de tutoriaux pour compiler le code source d'HL sur Linux (si cela aurait été préférable).

https://www.moddb.com/games/half-life/tutorials/introduction-to-goldsrc-programming-setting-up-visual-studio

**Comment by sixcentgeorge** [comment]
merci pour ces reponses et ces liens.. j aime bcp : 

Appendix B |   | C++ Updates
-- | -- | --
B.1 |   | Introduction to C++11
B.2 |   | Introduction to C++14
B.3 |   | Introduction to C++17

je connais toute cette merde de c++ et maintenant c# .. mais c est beaucoup trop idiot pour moi..
c est tellement mal fichu que comme on le vois dans ta longue liste de projet comme dans celle de solokiller.. et celle d autres "tchetchenes" amis ukrainiens du dumby dumpy trumpy et ses potes juyfs qui "give no : credits; but eat them 4 free" : y a pas un seul de vos truc qui compile.. , y a aucun release..
comme je disais au dessus au sujet de du dernier jeux de valve : qui est pas gratuit pour les heureux acheteurs du complete pack valve mais pour ceux qui ont achete des lunette a 1000 euro . tout ca c est du disney land..entre les mains des "banksters" qui pressent pour en faire sortir tout le jus.. comme ils faisaient avec les fillettes genre brit-brit : qui finissent en psychiatrie.. ca coute moins cher que de produire des dessins animes.... mais bon.. ils ont plus un cote : partage de la misere que "film a gogo" comme on peut le voir avec avatar 2 et les autres.. qui devait sortir a noel 2019.. peut etre en 21...  si les gens ont les 40 euros pour payer leurs ticket de cinema... c est aussi la vrai "face" du reve us.. les usa malgre tout ces "reveurs" n en reste pas moins qu un gigantesque terrain vert...ce qui n est pas le cas du reste du monde avec des villes et villages qui ont une histoire et de nombreux amenagements et lieu de vie...

merci pour tes efforts .. je vais casser les pieds ailleurs.. ce github est plutot "nullards zone" comme lindkin...  je produirais ma beta avec peu de monstres .. peut etre ca plaira a des ptites filles et ptit gars qui ont la chance de reussir leurs compilations.. 
n hesite pas a me recontacter

**Comment by sixcentgeorge** [comment]
j aime beaucoup le coup de pub "gratuite" de chez m8dbB :
I want to thank Malortie for his Visual Studio 2015 compatible version of the Half-Life SDK which I am sure many of you will find useful.
tu ne l aurais pas dans une machine virtuelle : le windows avec le sdk avec le visual studio ?

une archive 7zip facile a utiliser comme mon iso grml server pour svencoop... 
le coup de la video svencoop .. je programme un pitdrone.. avec du script.. c est tres fort.. surtout que ca fait longtemps que le monstre existe dans svencoop..il a fait partie de la grosse fournee initiale du vol de gearbox.. sur lequel c est batie svencoop..
a propos des roulures de chez moddb.. : y marche a voile et a vapeur : comme des tantouzes de trump...
y m ont flingue avec mon second mod : assault strike ..puis ont reuploade les fichiers.. et pareil avec mon premier mod que j avais demande qu ils n affichent plus.. et la pour le dernier : re bang : https://www.moddb.com/mods/hell-lifes
tu as des explications ? surement du meme tonneau que les ricains et leur fameuse victoire sur les nazis et les japs.. eux qui n ont eu qu a subir que 0.4 millions de mort , leurs freres juyfs 4 M et nos tres grands et amis de longues dates : les russes 40 Millions de morts  sur un total de ?????  c est comme pour les bombes atomiques dont ils se sont servi au japon.. ou bien les fusees v2.. pour batir la nasa avec des nazis.. et d'ailleurs le vivier sud-africain lui sert pour les remplacer : les nazis.. c est elon musk .. le nouveau "chef" ?????  enfin bon tout ca c est de la bouillie angliche dont ils ne voulaient pas chez eux .. c est dire si cela : pue...  [lol] [ australiens et ricains.. bien sur ]
que pour mon second mod comme pour le dernier.. les effacassages se font dans la froideur de la nuit sans prevenir... enfin bon : un site presque mort comme la plupart ayant a voir avec half-life...ils sont tous ou presque disparus...c est comme hl3 que personne ne reclame alors que le 2 l a bcp ete..
c est sur qu avec de tels frequentations..ca ne laisse pas beaucoup de temps pour soi...
en tout cas un site asiatique ca ferait peut etre mieux l affaire .. y sont travailleurs les chinois.. et intelligents..et surtout pas chers..  un site ou y en aurait prets a me faire mes dlls ca serait top.. comme dit l article half life sdk c etait du "c" et les mid ninetee's...
et sinon tu as un nom de membre au forum svencoop .. ? tu as peux etre connu sixcentgeorge ? le gars y se fait inviter au beta test pour se faire voler , depouiller... [un gros machin bien ricain ca: avec l appat du grand reve....]  et ton avis sur les bugs que j ai trouve dans toutes ces pitreries de projet de github .. svencoop inclus..   marrants toutes ces merdasses de programmation minable...voir super minable.. y faut oser le dire.. ewt surtout avoir la cervelle qui comprend ce qui se passe, savoir lire le taskman..  le coup du software a vide qu a une loop a fond : faut etre un nullard pour pas le voir.. et pas besoin d outils en sus.. encore des softwares compiles par visual studio de M$ .. et 100% sans errors ...garantie..  trop mort de rire...
j attend le vhd..du programmeur..
